"use client";
// src/features/landing/FeatureShowcase.tsx
import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Brain, Map, PiggyBank, Users } from "lucide-react";
import { Badge } from "@/components/ui/Badge";

const TABS = [
  {
    id: "ai",
    icon: Brain,
    label: "AI Builder",
    title: "Itineraries Generated by AI",
    description: "Tell Traveloop your destination, dates, and style. The AI generates a complete day-by-day plan with activities, restaurants, and transport — optimized for time and budget.",
    preview: {
      items: [
        { time: "9:00 AM", activity: "Senso-ji Temple", type: "Culture", cost: "$0" },
        { time: "11:30 AM", activity: "Tsukiji Fish Market", type: "Food", cost: "$25" },
        { time: "2:00 PM", activity: "Shibuya Crossing", type: "Sightseeing", cost: "$0" },
        { time: "5:00 PM", activity: "TeamLab Planets", type: "Art", cost: "$35" },
        { time: "8:00 PM", activity: "Shinjuku Izakaya Dinner", type: "Food", cost: "$40" },
      ]
    }
  },
  {
    id: "map",
    icon: Map,
    label: "Maps",
    title: "Visualize Your Entire Journey",
    description: "See your complete route on an interactive map. Animated paths connect your stops, with markers for hotels, restaurants, and attractions.",
    preview: null,
  },
  {
    id: "budget",
    icon: PiggyBank,
    label: "Budget",
    title: "Never Overspend Again",
    description: "Track every expense by category. Real-time alerts when you're approaching limits. Beautiful charts show exactly where your money went.",
    preview: {
      categories: [
        { name: "Flights", spent: 780, budget: 900, color: "bg-brand-500" },
        { name: "Hotels", spent: 420, budget: 500, color: "bg-accent-500" },
        { name: "Food", spent: 180, budget: 300, color: "bg-emerald-500" },
        { name: "Activities", spent: 95, budget: 200, color: "bg-amber-500" },
      ]
    }
  },
  {
    id: "collab",
    icon: Users,
    label: "Collaborate",
    title: "Plan Together, Travel Together",
    description: "Invite your travel crew. Everyone edits in real-time. Vote on activities, share notes, and stay in sync — no matter the timezone.",
    preview: null,
  },
];

export function FeatureShowcase() {
  const [active, setActive] = useState("ai");
  const activeTab = TABS.find((t) => t.id === active)!;

  return (
    <section className="py-24 px-4">
      <div className="max-w-6xl mx-auto">
        <div className="text-center mb-12">
          <Badge variant="primary" className="mb-4">Core Features</Badge>
          <h2 className="text-display text-4xl md:text-5xl mb-4">Your Complete Travel Companion</h2>
        </div>

        {/* Tab Pills */}
        <div className="flex flex-wrap items-center justify-center gap-2 mb-10">
          {TABS.map((tab) => (
            <button
              key={tab.id}
              onClick={() => setActive(tab.id)}
              className={`flex items-center gap-2 px-4 py-2.5 rounded-xl text-sm font-medium transition-all ${
                active === tab.id
                  ? "gradient-brand text-white shadow-lg shadow-brand-500/30"
                  : "glass border border-white/[0.06] text-surface-400 hover:text-surface-200"
              }`}
            >
              <tab.icon size={15} />
              {tab.label}
            </button>
          ))}
        </div>

        {/* Content */}
        <AnimatePresence mode="wait">
          <motion.div
            key={active}
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -20 }}
            transition={{ duration: 0.35 }}
            className="grid grid-cols-1 lg:grid-cols-2 gap-8 items-center"
          >
            {/* Text */}
            <div>
              <h3 className="text-3xl font-bold text-surface-50 mb-4">{activeTab.title}</h3>
              <p className="text-surface-400 text-lg leading-relaxed">{activeTab.description}</p>
            </div>

            {/* Preview Panel */}
            <div className="glass-light border border-white/[0.06] rounded-2xl p-6 min-h-64">
              {active === "ai" && activeTab.preview && (
                <div className="space-y-3">
                  <p className="text-xs font-semibold text-surface-500 uppercase tracking-wider mb-4">📍 Tokyo — Day 1</p>
                  {activeTab.preview.items?.map((item: any, i: number) => (
                    <motion.div
                      key={item.activity}
                      initial={{ opacity: 0, x: -20 }}
                      animate={{ opacity: 1, x: 0 }}
                      transition={{ delay: i * 0.08 }}
                      className="flex items-center gap-3 p-3 rounded-xl bg-surface-800/40 border border-white/[0.04]"
                    >
                      <span className="text-xs text-surface-500 w-16 flex-shrink-0">{item.time}</span>
                      <div className="flex-1">
                        <p className="text-sm font-medium text-surface-200">{item.activity}</p>
                        <p className="text-xs text-surface-500">{item.type}</p>
                      </div>
                      <span className="text-xs text-brand-400 font-medium">{item.cost}</span>
                    </motion.div>
                  ))}
                </div>
              )}
              {active === "budget" && activeTab.preview && (
                <div className="space-y-4">
                  <p className="text-xs font-semibold text-surface-500 uppercase tracking-wider mb-4">💰 Budget Overview</p>
                  {activeTab.preview.categories?.map((cat: any, i: number) => (
                    <div key={cat.name}>
                      <div className="flex justify-between text-sm mb-1.5">
                        <span className="text-surface-300">{cat.name}</span>
                        <span className="text-surface-400">${cat.spent} / ${cat.budget}</span>
                      </div>
                      <div className="h-2 bg-surface-800 rounded-full overflow-hidden">
                        <motion.div
                          initial={{ width: 0 }}
                          animate={{ width: `${(cat.spent / cat.budget) * 100}%` }}
                          transition={{ duration: 1, delay: i * 0.15, ease: "easeOut" }}
                          className={`h-full rounded-full ${cat.color}`}
                        />
                      </div>
                    </div>
                  ))}
                </div>
              )}
              {(active === "map" || active === "collab") && (
                <div className="flex items-center justify-center h-48 text-surface-600">
                  <activeTab.icon size={48} className="opacity-20" />
                </div>
              )}
            </div>
          </motion.div>
        </AnimatePresence>
      </div>
    </section>
  );
}
